- README.rst
- src/elexclarity/cli.py
- src/elexclarity/client.py
- src/elexclarity/convert.py
- src/elexclarity/formatters.py
- tests/fixtures/2020-11-03_GA.xml
- tests/fixtures/atkinson_precincts_2020-11-03_GA_G_P.xml
- tests/test_convert.py
Builds on @anthonyjpesce's existing PR. This PR adds formatting for county-level results and some other clean-up:
- County-level formatting (generalizes + refactors some code to handle both precinct and county subunits)
- Handle Clarity data when only one `Contest` is present 
- Adds fixture for state-level GA results for only two contests at `tests/fixtures/2020-11-03_GA.xml` 
- Adds fixture for precinct-level GA results with only one contest at `tests/fixtures/atkinson_precincts_2020-11-03_GA_G_P.xml` 
Currently, county IDs are formatted as `{fips}_{county_name}`, e.g. `13217_newton` to match the way we're formatting precinct names, but we can change this to just be the fips code to match our ap/edison formatters too. 
``elexclarity 105369 GA --level=county``
``elexclarity 105369 GA …
> Feature: Format counties

- src/elexclarity/convert.py
- src/elexclarity/formatters/results.py
- tests/test_convert.py
This makes two little improvements onto #8:
- It fixes a bug that occurred when calling `.convert` with a single result object (rather than a list)
- It allows the use of an `officeID` param to filter results during the formatting step
> Fix convert bug and allow officeID filtering

- setup.py
- src/elexclarity/formatters/settings.py
- tests/formatters/test_settings.py
Since the `get_county_results` method requires `county_name`, `county_id`, and `county_version`, I think it makes sense to include all three of those in a settings-style output.
I suppose we could theoretically do a reverse lookup from the FIPS code to name, but there's all sorts of formatting edge cases (e.g. `DeKalb`, `Jeff_Davis`, etc). It also seems potentially more generalizable to other states if we pass around `name`, rather than relying on a static mapping. (But if you feel strongly about another approach, I'm happy to adjust!)
[ELECT-1599]
Run a settings export, and make sure each county has a `name`, `clarityId`, and `version` attribute.
```
elexclarity 105369 GA --outputType=settings --officeID=S,S2
```
[ELECT-1599]: https://arcpublishing.atlassian.net/browse/ELECT-1599
> feat: Include county name in settings exports

- src/elexclarity/formatters/base.py
The Jan. 5 Georgia Runoff has an `election_name` of "January 5, 2021 Federal Runoff."
In the longer term, we should probably find a better way of setting the election type — but for now we can add "Runoff" to the list of general-election types as a quick and easy fix.
CLI commands for the Jan. 5 runoff should work:
```
elexclarity 107556 GA --level=county --officeID=S,S2
elexclarity 107556 GA --level=county --outputType=settings --officeID=S,S2
```
(Precinct results appear to not be available yet.)
> fix: Count runoffs as race_type "G"

- CHANGELOG.md
- README.rst
- setup.py
- src/elexclarity/cli.py
- src/elexclarity/convert.py
- src/elexclarity/formatters/results.py
- src/elexclarity/formatters/settings.py
- tests/fixtures/results/ga_atkinson_precincts_11-3.xml
- tests/formatters/test_results.py
- tests/formatters/test_settings.py
- tests/test_convert.py
We need a way to signal that a precinct has fully reported its results. This PR adds two different methods of doing so and a corresponding CLI flag for switching between those methods (`voteTypes` and `percentReporting`).
The `voteTypes` method checks that _some_ votes have been reported for each vote type (early, absentee, day of in person) other than provisional in a given precinct. This is happening per-race so there are a couple ways that it could be inaccurate.
The `percentReporting` method uses the `percentReporting` field which is populated on every precinct inside a `VoterTurnout` block in every precinct detail xml file. This field basically can't be holding a percentage value because it is set to 4 for every precinct in every single file I have looked at. There are, however, 4 …
> Feature: adds voteCompletionMode parameter

- src/elexclarity/formatters/const.py
Adds office names for Gov, Senate, and Sec of State races. 
Clarity site: [https://results.enr.clarityelections.com/GA/113667/web.285569/](https://results.enr.clarityelections.com/GA/113667/web.285569/ )
`elexclarity 113667 GA --level=precinct --officeID=G`
`elexclarity 113667 GA --level=precinct --officeID=S`
`elexclarity 113667 GA --level=precinct --officeID=R`
> Feature: Add GA primaries office names

- src/elexclarity/client.py
If the second version ID we try in the client for county precincts fails, handle that exception, too.
```sh
elexclarity 113667 GA --level=precinct --officeID=G
```
> fix: add more exception handling for client

- src/elexclarity/formatters/base.py
- src/elexclarity/formatters/results.py
- tests/formatters/test_results.py
I noticed three things about `elex-clarity` that seemed different than how `elex-state` handles precincts:
1. It groups precincts into county/race keys by adding the county ID to the end of `race_id`. So for a governor's race, for instance, there's one race per county with the precincts as subunits of each county/race pair, e.g. `2022-05-24_GA_R_G_13131` where `13131` is the county FIPS.
2. It doesn't add county ID to the precinct subunit ID.
3. It uses an underscore to slugify the precinct name, rather than a dash.
This draft PR does not address 1 and assumes this is expected behavior.
It does address 2 and 3 by adding the `county_id` to precinct IDs and uses a dash to slugify precinct names after that, so a precinct ID of `pearson_city` becomes `13003_pearson-city`.
```sh
elexclarity …
```
> Add `county_id` to precinct IDs, use dash to slugify precinct names

- src/elexclarity/cli.py
Removes a trailing slash from the default Clarity base URL, which causes our requests to contain two slashes (because the client adds a slash):
```
https://results.enr.clarityelections.com//IA/115641/current_ver.txt
```
That doesn't seem to break anything, but I'd rather our URLs be precise.
Ran the following:
```sh
elexclarity 115641 IA --level=precinct
```
I had to add some office mappings in `src/elexclarity/formatters/const.py` like these to get the command to complete:
```python
"IA": {
"United States Senator": "S",
"United States Representative": "H",
"Governor": "G",
"Secretary of State": "R"
}
```
(That's going in [this separate PR](#26).)
But once I did it worked.
> fix: remove extraneous slash from Clarity base URL

- src/elexclarity/client.py
Clarity results sites are returning `403 Client Error: Forbidden` when we send Python's default user agent or a custom WaPo user agent. This is likely a result of applying a blanket Web Application Firewall rule meant to generally block bots as part of an application security push. CDN/WAF providers have these sorts of rules as options. This fakes the user agent to appear as though the user is using a Safari web browser. That lets us through.
```sh
tox
elexclarity 113667 GA --officeID=S --level=precinct
```
> feat: fake the user agent

- src/elexclarity/formatters/base.py
- src/elexclarity/formatters/const.py
This PR partially matches office IDs in three states, so even if one county decides to call their Senate contest "US Senate/ Senado de los EE.UU. - Rep," we still match it. This includes a relatively broad list of potential names for each state, but each is unlikely to match incorrect contest names, given "U.S. Rep" is unlikely to be anything other than a contest for a United States House Representative. In effect, this adds Iowa and Arkansas to Clarity and is the first step towards adding U.S. House support for Georgia (the second step is parsing out the House district, see #29).
```sh
tox
elexclarity 106126 AR --level=precinct --countyName=Arkansas
elexclarity 113669 GA --level=precinct --countyName=Appling
elexclarity 115642 IA --level=precinct --countyName=Adair
```
> feat: partially match office IDs for AR, GA, IA

- src/elexclarity/formatters/base.py
- src/elexclarity/formatters/results.py
- tests/formatters/test_results.py
This PR builds on #28 to add district numbers to IDs for U.S. House races to elex-clarity. For instance, `2022-11-08_IA_G_H_3` for the U.S. House race in the 3rd district of the Iowa general election. It also adds a test.
```sh
tox
elexclarity 115641 IA --officeID=H
```
> feat: add district number to U.S. house office ID

- src/elexclarity/formatters/base.py
- tests/formatters/test_base.py
This bulletproofs the county mapping lookup, which was erroring on a county with the value "Hot_Spring" in the Arkansas test election. It also reduces the need for [some of the hacks](https://github.com/WPMedia/elex-data-importer/blob/080f2a13d489516f0fbc9cce4bf7b13936c39a79/elexdata/events/imports/clarity.py#L57-L61) that have been made to work around this issue for Georgia in data importer.
```sh
elexclarity 115767 AR --officeID=S,H,G --level=precinct --countyMapping='{"Hot_Spring":"5754"}'
tox
```
> fix: fall back when looking up county

- README.rst
Seeing the following when we try to deploy:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
The description failed to render in the default format of              
reStructuredText. See https://pypi.org/help/#description-content-type  
for more information.      
```
Ran `rst-lint` on README.rst, which is pulled into setup.py as an extended description and got:
```
WARNING README.rst:140 Inline literal start-string without end-string.
```
This PR adds an end-string to the literal.
```sh
pip install restructuredtext_lint
rst-lint README.rst
```
> chore: properly end literal string in README.rst

- src/elexclarity/formatters/base.py
- tests/formatters/test_results.py
This reverses part of #20 to remove the county ID from the precinct identifier, so that the importer Clarity state machine doesn't add it a second time, like `2022-11-08_IA_G_S_19181_19181_virginia`. The precinct ID will therefore just `virginia` in that case, and the race ID will be `2022-11-08_IA_G_S_19181`, together they will be `2022-11-08_IA_G_S_19181_virginia`.
```sh
tox
```
> fix: remove county ID from precinct ID

- src/elexclarity/cli.py
- src/elexclarity/convert.py
- src/elexclarity/formatters/base.py
- src/elexclarity/formatters/results.py
This PR adds a feature to elex-clarity to map candidate IDs using a mapping fed from the CLI or the API.
```sh
elexclarity 115470 GA --level=precinct --officeID=S --countyName=Baker --candidateMapping='{"herschel_junior_walker_rep":"herschel_junior_walker_gop"}' > out.json
```
> feat: add candidate mapping

- src/elexclarity/formatters/base.py
- src/elexclarity/formatters/results.py
- tests/formatters/test_results.py
This PR reformats candidate IDs to look closer to elex-state IDs, e.g. `2022-05-24_GA_D_S_DEM_tamara_johnson_shealey` adding the `race_id` and when available, `party`.
```sh
elexclarity 113669 GA --level=precinct --officeID=S --countyName=Appling
```
```js
"2022-05-24_GA_D_S": {
"id": "2022-05-24_GA_D_S",
"source": "clarity",
"precinctsReportingPct": 100.0,
"counts": {
"2022-05-24_GA_D_S_DEM_tamara_johnson_shealey": 22,
"2022-05-24_GA_D_S_DEM_raphael_warnock_i": 523
},
```
```js
"2022-05-24_GA_D_S": {
"id": "2022-05-24_GA_D_S",
"source": "clarity",
"precinctsReportingPct": 100.0,
"counts": {
"tamara_johnson_shealey": 22,
"raphael_warnock_i": 523
},
```
> feat: add race ID and party to candidate ID

- src/elexclarity/formatters/base.py
- src/elexclarity/formatters/const.py
- src/elexclarity/formatters/results.py
- tests/test_convert.py
This PR adds votes broken down by type to each subunit. It reports those in a `voteTypes` key, slugifying each vote type and allowing multiple vote types to be mapped into a single standard vote type defined per state (in Arkansas we use this to map `early-vote-north` and `early-vote-south`, observed in at least one case, to `early-vote`).
The result looks like this:
```json
"baker_milford": {
"id": "baker_milford",
"counts": {
"2022-11-08_GA_G_S_herschel_junior_walker_rep": 198,
"2022-11-08_GA_G_S_raphael_warnock_i_dem": 76,
"2022-11-08_GA_G_S_chase_oliver_l": 3
},
"voteTypes": {
"absentee-by-mail": {
"2022-11-08_GA_G_S_herschel_junior_walker_rep": 12,
"2022-11-08_GA_G_S_raphael_warnock_i_dem": 18,
"2022-11-08_GA_G_S_chase_oliver_l": 0
},
"advance-voting": { …
```
> feat: add count by vote type to subunits

- README.rst
- src/elexclarity/cli.py
- src/elexclarity/convert.py
- src/elexclarity/formatters/results.py
- tests/formatters/test_results.py
This PR adds an override to allow specifying a reporting status for precincts in a specific county. To use, you add `--precinctsReportingPct='{"bacon":0}'`, specifying the county IDs and reporting percents, to the CLI. This sets all the subunits to the same reporting percent, as well as overall result, so the above example will set all subunits in Bacon county to `0` as well as the overall percent for Bacon county itself.
[ELEX-1959](https://arcpublishing.atlassian.net/browse/ELEX-1959)
```sh
tox
elexclarity 115470 GA --level=precinct --officeID=P --countyName=Bacon --voteCompletionMode=combined --precinctsReportingPct='{"bacon":0}' --filename="tests/fixtures/results/ga_bacon_precincts_11-3.xml"
```
```js
{
"2020-11-03_GA_G_P_bacon": {
"id": "2020-11-03_GA_G_P_bacon",
"source": "clarity", …
```
> feat: add precincts reporting percent override

- src/elexclarity/formatters/results.py
- tests/formatters/test_results.py
This PR adds a way to override the election date when formatting results by using the date supplied when invoking elex-clarity. There is no CLI argument for this, but the convert method does get the date from importer, and this lets us set that to whatever we want, allowing us to use one election to stand in for another when testing.
```sh
tox
```
> feat: add election date override

- README.rst
- src/elexclarity/formatters/const.py
- src/elexclarity/formatters/results.py
- tests/formatters/test_results.py
This PR adds a rudimentary reporting status categorical flag for subunits. Right now it is limited to two states: `REPORTING` and `NOT_REPORTING`. This is based on whatever `voteCompletionMode` is set, but critically it does not respect any reporting percent overrides added in #52 (this seems inconsistent, but we're doing this very deliberately to monitor the original reporting status even when overridden).
Ideally we'd like to expand this to more fully reflect elex-ap's range of values, including possibly `EARLY_VOTING_REPORTING`, `LIMITED_REPORTING`, `EST_FULLY_REPORTING` and `CERTIFIED`, but not today.
Note: This PR ladders on #52 and should be merged after it.
[ELEX-1966](https://arcpublishing.atlassian.net/browse/ELEX-1966)
```sh
elexclarity 115470 GA --level=precinct --officeID=P …
```
> feat: add reporting status flag for subunits

- src/elexclarity/formatters/base.py
This PR removes leading numbers from Gwinnett precinct identifiers to improve consistency between our data and precinct identifiers in the runoff results. It also adds some suffixes from Chatham county precinct IDs.
```sh
elexclarity 116632 GA --countyName=Gwinnett --level=precinct --countyMapping='{"Gwinnett":"13135"}'
elexclarity 116590 GA --countyName=Chatham --level=precinct
```
```json
"13135_baycreek-c": {
"id": "13135_baycreek-c",
```
```json
"gwinnett_156-baycreek-j": {
"id": "13135_156-baycreek-j",
```
> feat: clean GA precinct IDs
